# Channels session — restart-on-idle scheduled task installer (ADR-009).
#
# The Linux unit pair (caishen-channels-restart.service + .timer) fires
# every 30 minutes during quiet operator hours and restarts the Channels
# service to mitigate long-lived-session drift. Mute marker in
# channels_health.mute_alarm_until suppresses the restart during active
# windows.
#
# This Windows installer creates the equivalent via Windows Task Scheduler:
#   - Trigger: every 30 minutes, indefinitely
#   - Action:  PowerShell script that (1) checks the mute marker against the
#     channels_health row, (2) inserts an audit row, (3) restarts the NSSM
#     service.
#
# Constitution §3 (audit-or-abort): the audit row insert happens BEFORE
# the restart so an abort there leaves the service running, not silently
# dead.
#
# Usage (run as Administrator on the VPS):
#   .\install-restart-on-idle-task.ps1 `
#       -RepoRoot      "C:\caishen\caishenye" `
#       -EnvFile       "C:\caishen\channels.env" `
#       -ServiceName   "caishen-channels" `
#       -TaskName      "caishen-channels-restart-on-idle" `
#       -PsqlPath      "C:\Program Files\PostgreSQL\16\bin\psql.exe"

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$RepoRoot,

    [Parameter(Mandatory = $true)]
    [string]$EnvFile,

    [string]$ServiceName = "caishen-channels",

    [string]$TaskName = "caishen-channels-restart-on-idle",

    [Parameter(Mandatory = $true)]
    [string]$PsqlPath
)

$ErrorActionPreference = "Stop"

# ----- 0. Pre-flight ---------------------------------------------------------

if (-not (Test-Path $EnvFile)) {
    throw "Environment file missing: $EnvFile (must contain DATABASE_URL + CAISHEN_TENANT_ID)"
}

if (-not (Test-Path $PsqlPath)) {
    throw "psql.exe not found: $PsqlPath. Install PostgreSQL client OR use the libpq bundled with your driver."
}

# ----- 1. Materialize the runner script -------------------------------------
#
# Task Scheduler triggers an inline PowerShell command; we generate a small
# script next to this installer and invoke it from the trigger action.

$runnerPath = Join-Path $RepoRoot "infra\vps\windows\restart-on-idle-runner.ps1"
$runnerDir = Split-Path $runnerPath -Parent
if (-not (Test-Path $runnerDir)) {
    New-Item -ItemType Directory -Path $runnerDir -Force | Out-Null
}

$runnerContent = @"
# AUTO-GENERATED by install-restart-on-idle-task.ps1.
# Operator-managed; modify install-restart-on-idle-task.ps1 instead and re-run.
#
# Mirrors infra/vps/systemd/restart-on-idle behavior:
#   1. Read mute marker from channels_health.
#   2. If muted, exit 0 silently.
#   3. Otherwise insert audit row (constitution §3 audit-before-action).
#   4. Restart NSSM service.

`$ErrorActionPreference = "Stop"

# Load env vars from the file (KEY=VALUE, # comments, blank lines).
Get-Content "$EnvFile" | ForEach-Object {
    if (`$_ -match '^\s*#' -or `$_ -notmatch '=') { return }
    `$key, `$value = `$_ -split '=', 2
    [Environment]::SetEnvironmentVariable(`$key.Trim(), `$value.Trim(), 'Process')
}

`$tenant = `$env:CAISHEN_TENANT_ID
`$dbUrl = `$env:DATABASE_URL

if (-not `$tenant) { throw 'CAISHEN_TENANT_ID not set' }
if (-not `$dbUrl) { throw 'DATABASE_URL not set' }

# 1. Mute marker check.
`$muted = & "$PsqlPath" "`$dbUrl" -A -t -c @"
SELECT EXISTS (
  SELECT 1 FROM channels_health
  WHERE tenant_id = `$tenant
    AND mute_alarm_until IS NOT NULL
    AND mute_alarm_until > NOW()
);
"@

if (`$muted.Trim() -eq 't') {
    Write-Host '[restart-on-idle] mute_alarm_until is in the future — skipping restart.'
    exit 0
}

# 2. Audit row before action (constitution §3).
& "$PsqlPath" "`$dbUrl" -v ON_ERROR_STOP=1 -c @"
INSERT INTO channels_health (tenant_id, checked_at, healthy_bool, restart_reason)
VALUES (`$tenant, NOW(), true, 'scheduled_idle');
"@
if (`$LASTEXITCODE -ne 0) {
    throw 'Audit insert failed; aborting restart per constitution §3.'
}

# 3. Restart the service.
Restart-Service -Name '$ServiceName' -Force
Write-Host "[restart-on-idle] restart complete at `$([DateTime]::UtcNow.ToString('o'))"
"@

Set-Content -Path $runnerPath -Value $runnerContent -Encoding UTF8

Write-Host "Runner script written to: $runnerPath"

# ----- 2. Register the scheduled task ---------------------------------------

# If task already exists, remove it (idempotent re-install).
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "Removing existing task '$TaskName' for re-install..."
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$runnerPath`""

# Trigger: every 30 minutes, starting 30 min from now, indefinitely.
$trigger = New-ScheduledTaskTrigger `
    -Once `
    -At ((Get-Date).AddMinutes(30)) `
    -RepetitionInterval (New-TimeSpan -Minutes 30) `
    -RepetitionDuration ([TimeSpan]::FromDays(36500))

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 5)

# Run as SYSTEM (no interactive login required, matches systemd User=root model).
$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -RunLevel Highest

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "ADR-009 — periodic restart of caishen-channels every 30 min during idle. Honors channels_health.mute_alarm_until marker." `
    | Out-Null

Write-Host ""
Write-Host "OK — task '$TaskName' registered. First run in 30 min."
Write-Host ""
Write-Host "Verify: Get-ScheduledTask -TaskName '$TaskName'"
Write-Host "Manual fire (test): Start-ScheduledTask -TaskName '$TaskName'"
